/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Rental Mobil");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Mobil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Pelanggan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Transaksi");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Laporan Mobil");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Laporan Pelanggan");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("Laporan Transaksi");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new FrameMobil().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new FramePelanggan().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new FrameTransaksi().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rental_mobil", "root", "");
            Statement stmt = conn.createStatement();

            // Buat dokumen PDF
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream("Laporan Data Mobil.pdf"));
            document.open();

            // Tambahkan judul laporan
            Font font = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Paragraph judul = new Paragraph("Laporan Data Mobil", font);
            judul.setAlignment(Element.ALIGN_CENTER);
            document.add(judul);
            
            // Tambahkan tanggal laporan
            Date tanggal = new Date();
            Paragraph tanggalLaporan = new Paragraph("Tanggal: " + tanggal.toString());
            tanggalLaporan.setAlignment(Element.ALIGN_CENTER);
            document.add(tanggalLaporan);
            document.add(new Paragraph("\n\n")); 

            // Buat tabel laporan
            PdfPTable table = new PdfPTable(6);
            table.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell(new Phrase("No"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Kode Mobil"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Brand"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Model"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("No. Polisi"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Harga Sewa"));
            cell.setBorderWidth(1);
            table.addCell(cell);

            // Isi tabel laporan dengan data dari database
            ResultSet rs = stmt.executeQuery("SELECT * FROM mobil");
            int no = 1;
            while (rs.next()) {
                table.addCell(String.valueOf(no));
                table.addCell(rs.getString("kode_mobil"));
                table.addCell(rs.getString("brand"));
                table.addCell(rs.getString("model"));
                table.addCell(rs.getString("nopol"));
                table.addCell(rs.getString("harga"));
                no++;
            }

            // Tambahkan tabel laporan ke dokumen PDF
            document.add(table);

            // Tutup dokumen PDF
            document.close();

            // Buka file PDF yang telah dibuat
            Desktop.getDesktop().open(new File("Laporan Data Mobil.pdf"));
        } catch (DocumentException | SQLException | IOException e) {
            JOptionPane.showMessageDialog(null, "Gagal membuat laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rental_mobil", "root", "");
            Statement stmt = conn.createStatement();

            // Buat dokumen PDF
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream("Laporan Data Pelanggan.pdf"));
            document.open();

            // Tambahkan judul laporan
            Font font = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Paragraph judul = new Paragraph("Laporan Data Pelanggan", font);
            judul.setAlignment(Element.ALIGN_CENTER);
            document.add(judul);

            // Tambahkan tanggal laporan
            Date tanggal = new Date();
            Paragraph tanggalLaporan = new Paragraph("Tanggal: " + tanggal.toString());
            tanggalLaporan.setAlignment(Element.ALIGN_CENTER);
            document.add(tanggalLaporan);

            // Tambahkan spasi antara tanggal dan tabel
            document.add(new Paragraph("\n\n"));

            // Buat tabel laporan
            PdfPTable table = new PdfPTable(5);
            table.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell(new Phrase("No"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Kode Pelanggan"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Nama"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Alamat"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("No. Telepon"));
            cell.setBorderWidth(1);
            table.addCell(cell);

            // Isi tabel laporan dengan data dari database
            ResultSet rs = stmt.executeQuery("SELECT * FROM pelanggan");
            int no = 1;
            while (rs.next()) {
                table.addCell(String.valueOf(no));
                table.addCell(rs.getString("kode_pelanggan"));
                table.addCell(rs.getString("nama"));
                table.addCell(rs.getString("alamat"));
                table.addCell(rs.getString("telepon"));
                no++;
            }

            // Tambahkan tabel laporan ke dokumen PDF
            document.add(table);

            // Tutup dokumen PDF
            document.close();

            // Buka file PDF yang telah dibuat
            Desktop.getDesktop().open(new File("Laporan Data Pelanggan.pdf"));
        } catch (DocumentException | SQLException | IOException e) {
            JOptionPane.showMessageDialog(null, "Gagal membuat laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rental_mobil", "root", "");
            Statement stmt = conn.createStatement();

            // Buat dokumen PDF
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream("Laporan Data Transaksi.pdf"));
            document.open();

            // Tambahkan judul laporan
            Font font = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Paragraph judul = new Paragraph("Laporan Data Transaksi", font);
            judul.setAlignment(Element.ALIGN_CENTER);
            document.add(judul);

            // Tambahkan tanggal laporan
            Date tanggal = new Date();
            Paragraph tanggalLaporan = new Paragraph("Tanggal: " + tanggal.toString());
            tanggalLaporan.setAlignment(Element.ALIGN_CENTER);
            document.add(tanggalLaporan);
            document.add(new Paragraph("\n\n"));

            // Buat tabel laporan
            PdfPTable table = new PdfPTable(7);
            table.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell(new Phrase("No"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Kode Pelanggan"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Kode Mobil"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Tanggal Sewa"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Tanggal Kembali"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Lama Sewa"));
            cell.setBorderWidth(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Total"));
            cell.setBorderWidth(1);
            table.addCell(cell);

            // Isi tabel laporan dengan data dari database
            ResultSet rs = stmt.executeQuery("SELECT * FROM transaksi");
            int no = 1;
            while (rs.next()) {
                table.addCell(String.valueOf(no));
                table.addCell(rs.getString("kode_pelanggan"));
                table.addCell(rs.getString("kode_mobil"));
                table.addCell(rs.getString("tgl_sewa"));
                table.addCell(rs.getString("tgl_kembali"));
                table.addCell(rs.getString("lama_sewa"));
                table.addCell(rs.getString("total"));
                no++;
            }

            // Tambahkan tabel laporan ke dokumen PDF
            document.add(table);

            // Tutup dokumen PDF
            document.close();

            // Buka file PDF yang telah dibuat
            Desktop.getDesktop().open(new File("Laporan Data Transaksi.pdf"));
        } catch (DocumentException | SQLException | IOException e) {
            JOptionPane.showMessageDialog(null, "Gagal membuat laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
